const fs = require('fs');

let content = fs.readFileSync('lib/data/events.ts', 'utf8');

// 1. Update UI-UX
content = content.replace(
  /id: 'ui-ux',[\s\S]*?isActive: true,\n  },/,
  `id: 'ui-ux',
    slug: 'ui-ux',
    title: 'AI WEB SPRINT',
    category: 'technical',
    tagline: 'AI-powered frontend development, creativity, UI design, problem solving and speed.',
    shortDesc: 'Participants receive a problem statement and must create the best frontend website using AI tools within the given time limit.',
    fullDesc: '**Team Size:** 2–4 Members\\n\\n**Objective:**\\nParticipants receive a problem statement and must create the best frontend website using AI tools within the given time limit.\\n\\n**Time Limit:** 20 Minutes\\n\\n**Focus:**\\nAI-powered frontend development, creativity, UI design, problem solving and speed.',
    date: '[SYMPOSIUM DATE]',
    time: '11:00 AM - 02:00 PM',
    venue: 'Design Studio Lab',
    fee: 100,
    teamSize: '2-4 Members',
    prizes: {
      first: '₹3,000 + Design Award',
      second: '₹1,500 + Certificate',
      third: 'Certificate of Merit',
    },
    coordinators: [
      { name: 'Sara', year: '4th Year', role: 'Lead Coordinator' },
      { name: 'Yumna', year: '2nd Year', role: 'Co-Coordinator' },
      { name: 'Sultan', year: '2nd Year', role: 'Co-Coordinator' },
    ],
    rules: [
      'The problem statement and requirements will be revealed only at the start of the event.',
      'Participants have 20 minutes to design and build the website.',
      'Any AI-powered website-building tool may be used.',
      'Only frontend/UI development is required.',
      'Backend functionality is not required.',
      'Pre-built projects are strictly prohibited.',
      'Previously prepared projects are strictly prohibited.',
      'Copied projects or content are strictly prohibited.',
      'The final website must satisfy the requirements in the problem statement.',
      'The final website link or output must be submitted before the deadline.',
      'No modifications are permitted after submission.',
      'The judges\\' decision will be final and binding.',
    ],
    rounds: [
      { title: 'Challenge Round', desc: '1. The problem statement and requirements are revealed only at the beginning of the event.\\n2. Participants analyze the problem statement.\\n3. Teams design and build a frontend website using AI-powered tools.\\n4. Participants have 20 minutes to complete the challenge.\\n5. The final website/output must be submitted before the time limit expires.\\n6. The submitted website is evaluated based on how well it satisfies the given requirements.' },
    ],
    judgingCriteria: [
      'User Experience and intuitive navigation flow',
      'Visual polish, typography, and color harmony',
      'Innovation and responsiveness of the prototype',
    ],
    iconName: 'Palette',
    badge: 'Creative',
    isActive: true,
  },`
);

// 2. Update E-Sports
content = content.replace(
  /id: 'e-sports',[\s\S]*?isActive: true,\n  },/,
  `id: 'e-sports',
    slug: 'e-sports',
    title: 'FREE FIRE TOURNAMENT',
    category: 'non-technical',
    subCategory: 'Gaming',
    tagline: 'Battle Royale Qualifier → Clash Squad Final',
    shortDesc: 'The top two teams from the Battle Royale points table qualify for the Clash Squad Final.',
    fullDesc: '**Tournament Format:**\\nBattle Royale Qualifier → Clash Squad Final\\n\\n**Qualification:**\\nThe top two teams from the Battle Royale points table qualify for the Clash Squad Final.\\n\\n**Scoring:**\\n\\n| Achievement | Points |\\n| ----------- | --------: |\\n| Each Kill | 5 Points |\\n| Booyah | 10 Points |\\n\\nThe team winning the Clash Squad Final will be declared the Tournament Winner.',
    date: '[SYMPOSIUM DATE]',
    time: '10:00 AM - 04:00 PM',
    venue: 'E-Sports Arena / Hall B',
    fee: 150,
    teamSize: 'Squad (4 Players)',
    prizes: {
      first: '₹5,000 + Winner Trophy',
      second: '₹2,500 + Runner-up Trophy',
      overall: 'Exclusive E-Sports Champion Medals',
    },
    coordinators: [
      { name: 'Rakesh', year: '2nd Year', role: 'Free Fire Coordinator' },
      { name: 'Reyas', year: '2nd Year', role: 'Free Fire Coordinator' },
      { name: '[Coordinator details pending]', year: '2nd Year', role: 'E-Football Coordinator' },
    ],
    rules: [
      '**General Rules:** All players and teams must follow organizer and coordinator instructions. Organizer decisions regarding procedures, disputes, penalties and results are final. Serious misconduct or deliberate conflicts may result in team disqualification. Players must maintain proper sportsmanship and respectful behavior.',
      '**Fair Play:** Panels, hacks, cheats, scripts and unauthorized third-party software are strictly prohibited. Emulators are strictly prohibited. Players must use the permitted mobile platform. Suspicious activity may be investigated by the organizers. Players must cooperate with verification if requested.',
      '**Clash Squad Restrictions:** Grenades and smoke bombs are not allowed. Gun skins are not allowed. Character skills are not allowed. Players must follow the gameplay settings announced before the match.',
      '**Disqualification:** If any team member uses a prohibited tool, hack, panel, emulator or unfair advantage, the entire team may be disqualified. Evidence of cheating or rule violations may be reviewed before the final decision. A disqualified team cannot continue the match or claim the winning position.',
      '**Winner Declaration:** The winner of the Clash Squad Final will be officially declared the Tournament Winner. The result announced by the organizers is official and final. Players or teams must not interfere with the official result after it has been announced.',
      '**Code of Conduct:** Participants must maintain respectful and professional behavior, follow organizer instructions, avoid disputes, play fairly and report cheating through proper channels.',
    ],
    rounds: [
      { title: 'ROUND 1 — BATTLE ROYALE QUALIFIER', desc: '1. The tournament begins with a Battle Royale match.\\n2. The BR match serves as the qualifying round.\\n3. Points are awarded based on kills and Booyah.\\n4. Each kill earns 5 points.\\n5. Booyah earns 10 points.\\n6. The final BR ranking is determined by total points.\\n7. The top two teams qualify for the Clash Squad Final.' },
      { title: 'TIE-BREAKER', desc: '1. If two teams have the same total points, a 4-round Clash Squad tie-breaker will be conducted.\\n2. The winner of the tie-breaker receives the qualification position.\\n3. The tie-breaker format and necessary adjustments will be decided by the organizers.' },
      { title: 'ROUND 2 — CLASH SQUAD FINAL', desc: '1. The two teams qualified from the BR round compete in the Clash Squad Final.\\n2. The number of rounds and match format will be announced by the organizers.\\n3. Necessary changes to the match format may be made based on tournament requirements.' },
    ],
    iconName: 'Gamepad2',
    badge: 'High Stakes',
    isActive: true,
  },`
);

// 3. Update Film Hunt
content = content.replace(
  /id: 'film-hunt',[\s\S]*?isActive: true,\n  },/,
  `id: 'film-hunt',
    slug: 'film-hunt',
    title: 'FILM HURT',
    category: 'non-technical',
    tagline: 'Movie and music-based challenge',
    shortDesc: 'Film Hurt is a movie and music-based challenge testing participants\\' knowledge.',
    fullDesc: '**Team Format:** 2 Members\\n\\n**Total Rounds:** 4\\n\\n**Special Rule:** Round 3 is the elimination round.\\n\\nFilm Hurt is a movie and music-based challenge testing participants\\' knowledge of:\\n* Movie background music\\n* Songs\\n* Movie connections\\n* Lyrics\\n* Actors\\n* Famous dialogues\\n\\nNo mobile phones or internet access are permitted during the rounds.\\nTeams must answer only when the host gives permission.',
    date: '[SYMPOSIUM DATE]',
    time: '11:30 AM - 01:30 PM',
    venue: 'Campus Quad & Media Lab',
    fee: 100,
    teamSize: '2 Members',
    prizes: {
      first: '₹2,500 + Cine Trophy',
      second: '₹1,200 + Certificate',
      third: 'Certificate of Merit',
    },
    coordinators: [
      { name: 'Mohamed Abdul Faazil A', year: '4th Year', role: 'Lead Coordinator' },
      { name: 'Tameem', year: '2nd Year', role: 'Co-Coordinator' },
      { name: 'Durgeh', year: '2nd Year', role: 'Co-Coordinator' },
    ],
    rules: [
      'Each team must consist of exactly 2 members.',
      'Mobile phones are not allowed during the rounds.',
      'Internet access is not allowed during the event.',
      'Teams must answer only when the host gives permission.',
      'Participants must follow the time limits for each round.',
      'Only answers given within the allotted time will be considered.',
      'Participants must not use outside assistance.',
      'Round 3 is the elimination round.',
      'Participants must follow all instructions given by the host and organizers.',
      'The organizers\\' decision will be final and binding.',
    ],
    rounds: [
      { title: 'ROUND 1 — BGM BLAST', desc: '**Concept:** Identify the movie/song from its background music.\\n\\n**Format:**\\n1. Play a 5–15 second BGM clip.\\n2. Stop the clip.\\n3. Team gets 10 seconds to answer.\\n4. Questions may require identifying a song or movie.\\n\\n**Rules:**\\n* Only the first answer is considered.\\n* If a team passes, the question may be opened to other teams.\\n* Replaying a clip may be prohibited or may carry reduced marks.\\n* Difficulty should progressively increase.' },
      { title: 'ROUND 2 — CONNECTION', desc: '**Concept:** Find the common connection between multiple movie-related clues.\\n\\n**Format:**\\n1. Display/play 3 clues initially.\\n2. Clues may include images or movie-related information.\\n3. Team gets 15 seconds to identify the connection.\\n4. If the team cannot answer, reveal the 4th clue.\\n\\n**Rules:**\\n* Teams must identify the common connection.\\n* A misleading clue may be included to increase difficulty.\\n* Answers must be given within the allotted time.\\n* Only the first valid answer is considered.' },
      { title: 'ROUND 3 — MISSING LYRICS (ELIMINATION ROUND)', desc: '**ELIMINATION ROUND**\\n\\n**Concept:** Test participants\\' knowledge of popular movie songs.\\n\\n**Format:**\\n1. Play a short portion of a song.\\n2. Stop/mute the song at a specific point.\\n3. Display the missing lyric.\\n4. Team must provide the next line.\\n5. Team gets 10 seconds to answer.\\n6. Performance in this round determines elimination.\\n\\n**Rules:**\\n* Only a short portion of the song will be played.\\n* The song must stop at a clear point.\\n* Answer must match the intended lyric.\\n* Participants cannot hum the answer.\\n* Participants cannot play the song from their phones.\\n* The answer must not be revealed until all teams have attempted.' },
      { title: 'ROUND 4 — FINAL ROUND', desc: '**Objective:** Identify movies, actors and famous dialogues using clues.\\n\\n**Team Format:** One participant gives/reads clues while the other participant discusses and guesses.\\n\\n**Time Limit:** 15 seconds per challenge.\\n\\n**Format:**\\n1. Host starts the timer after giving the first clue.\\n2. A secret card is given to one team member.\\n3. The card may contain: Actor name, Famous dialogue, Movie-related clue.\\n4. The participant provides clues.\\n5. The other participant attempts to identify the answer.\\n6. The answer must be identified within 15 seconds.\\n\\n**Winner:** The team that successfully completes the final challenge according to the event criteria will be declared the winner.' },
    ],
    iconName: 'Film',
    badge: 'Exciting',
    isActive: true,
  },`
);

// 4. Update Voice & Noise
content = content.replace(
  /id: 'voice-and-noise',[\s\S]*?isActive: true,\n  },/,
  `id: 'voice-and-noise',
    slug: 'voice-and-noise',
    title: 'VOICE & NOISE GAME',
    category: 'non-technical',
    tagline: 'Team Format: Teams/Pairs',
    shortDesc: 'The Guesser must identify words by watching the Speaker\\'s lips while wearing headphones with loud music.',
    fullDesc: '**Team Format:** Teams/Pairs\\n\\n**Roles:**\\n* One participant is the Speaker.\\n* One participant is the Guesser.\\n\\n**Objective:**\\nThe Guesser must identify words by watching the Speaker\\'s lips while wearing headphones with loud music.\\n\\n**Scoring:**\\nEvery correctly guessed word = 1 point.\\n\\n**Winner:**\\nThe team with the highest score wins.',
    date: '[SYMPOSIUM DATE]',
    time: '02:00 PM - 03:30 PM',
    venue: 'Acoustic Stage / Open Amphitheatre',
    fee: 80,
    teamSize: 'Teams/Pairs',
    prizes: {
      first: '₹2,000 + Certificate',
      second: '₹1,000 + Certificate',
      third: 'Certificate of Merit',
    },
    coordinators: [
      { name: 'Divya', year: '4th Year', role: 'Lead Coordinator' },
      { name: 'Kausmitha', year: '2nd Year', role: 'Co-Coordinator' },
      { name: 'Usna', year: '2nd Year', role: 'Co-Coordinator' },
    ],
    rules: [
      'The Speaker must say the selected word clearly.',
      'The Speaker cannot use hand gestures to communicate the answer.',
      'The Speaker cannot intentionally reveal the word through gestures.',
      'The word must not be shown to the Guesser.',
      'The Guesser must wear headphones with loud music.',
      'The Guesser must attempt to identify the word by watching the Speaker\\'s lips.',
      'No outside assistance is allowed.',
      'Only correctly guessed words receive points.',
      'Participants must switch roles when instructed.',
      'The team with the highest score wins.',
      'The organizers\\' decision will be final and binding.',
    ],
    rounds: [
      { title: 'Round Format', desc: '1. Divide participants into teams/pairs.\\n2. One participant becomes the Speaker.\\n3. The other participant becomes the Guesser.\\n4. The Guesser wears headphones with loud music.\\n5. The Speaker selects a word and says the actual word aloud.\\n6. The Guesser watches the Speaker\\'s lips and attempts to identify the word.\\n7. Set a time limit of approximately 30–60 seconds.\\n8. Each correctly guessed word earns 1 point.\\n9. After the time ends, participants switch roles.\\n10. Scores from both turns are calculated.' },
    ],
    iconName: 'Mic2',
    badge: 'Live',
    isActive: true,
  },`
);

// 5. Update Free Style -> Talent Show
content = content.replace(
  /id: 'free-style',[\s\S]*?isActive: true,\n  }/,
  `id: 'free-style',
    slug: 'free-style',
    title: 'TALENT SHOW',
    category: 'non-technical',
    tagline: 'A multi-category talent competition',
    shortDesc: 'A multi-category talent competition featuring singing, dancing, acting, comedy, mimicry, instrumental music, mime and live art.',
    fullDesc: '**OVERVIEW**\\n\\nA multi-category talent competition featuring singing, dancing, acting, comedy, mimicry, instrumental music, mime and live art.\\n\\nParticipants are evaluated based on category-specific judging criteria.\\n\\n**Categories:**\\n1. Singing\\n2. Dancing\\n3. Skit\\n4. Mono Act\\n5. Stand-Up Comedy\\n6. Mimicry\\n7. Instrumental Music\\n8. Mime\\n9. Live Art',
    date: '[SYMPOSIUM DATE]',
    time: '03:30 PM - 05:00 PM',
    venue: 'Main Open Stage',
    fee: 100,
    teamSize: 'Varies',
    prizes: {
      first: '₹3,000 + Trophy',
      second: '₹1,500 + Medal',
      third: 'Certificate of Merit',
    },
    coordinators: [
      { name: 'Aary', year: '4th Year', role: 'Lead Coordinator' },
      { name: 'Yones', year: '2nd Year', role: 'Co-Coordinator' },
    ],
    rules: [
      '**COMMON RULES:**',
      '1. Participants must register before the deadline.',
      '2. Performance time limits must be strictly followed.',
      '3. Participants should report 30 minutes before their performance.',
      '4. Music/audio/technical requirements must be submitted in advance.',
      '5. Participants are responsible for their own props and personal equipment.',
      '6. Fire, sharp objects, dangerous stunts and unsafe activities are strictly prohibited.',
      '7. Vulgar, offensive, discriminatory or inappropriate content is not permitted.',
      '8. Plagiarism or unauthorized use of another participant\\'s original work is prohibited.',
      '9. Participants must follow instructions from the organizing and technical teams.',
      '10. Time-limit violations may result in mark deductions.',
      '11. In case of a tie, the relevant higher-scoring criterion will be used as the tie-breaker.',
      '12. The judges\\' decision will be final and binding.',
      '**Singing:** Solo, duet or group performance is allowed. Maximum performance time is 5 minutes. Singing must be live; lip-syncing is not allowed. Karaoke/backing tracks or instruments are allowed.',
      '**Dancing:** Solo, duet or group performance is allowed. Maximum performance time is 5 minutes. Music must be submitted beforehand. Props and costumes are allowed. Dangerous stunts or lifts are prohibited.',
      '**Skit:** Group performance. Maximum duration is 7 minutes. Maximum 8 participants. Props are allowed but must be arranged by participants.',
      '**Mono Act:** Solo performance. Maximum duration is 5 minutes. Multiple characters may be portrayed. Props are allowed.',
      '**Stand-Up Comedy:** Solo performance. Maximum duration is 5 minutes. Original content is preferred. Abusive, vulgar, discriminatory or offensive jokes are prohibited.',
      '**Mimicry:** Solo performance. Maximum duration is 5 minutes. Multiple characters/voices are allowed. Content must remain respectful.',
      '**Instrumental Music:** Solo or group performance. Maximum duration is 5 minutes. Performance must be live.',
      '**Mime:** Solo or group performance. Maximum duration is 5 minutes. Spoken dialogue is not allowed. Props are allowed. Story/message should be communicated through actions and expressions.',
      '**Live Art:** Solo performance. Maximum duration is 10 minutes. Artwork must be created completely live on stage. Pre-prepared artwork is prohibited.',
    ],
    rounds: [
      { title: '1. SINGING', desc: '**Format:** Solo, duet or group\\n**Maximum Time:** 5 Minutes\\n\\n**Judging — 100 Marks**\\n* Voice & Pitch — 30\\n* Rhythm & Control — 20\\n* Expression — 20\\n* Stage Presence — 15\\n* Overall Performance — 15' },
      { title: '2. DANCING', desc: '**Format:** Solo, duet or group\\n**Maximum Time:** 5 Minutes\\n\\n**Judging — 100 Marks**\\n* Technique — 25\\n* Rhythm & Synchronization — 25\\n* Choreography — 20\\n* Expression — 15\\n* Stage Presence — 15' },
      { title: '3. SKIT', desc: '**Format:** Group\\n**Maximum Time:** 7 Minutes\\n**Maximum Participants:** 8\\n\\n**Judging — 100 Marks**\\n* Acting — 25\\n* Story/Concept — 20\\n* Dialogue Delivery — 20\\n* Team Coordination — 20\\n* Overall Impact — 15' },
      { title: '4. MONO ACT', desc: '**Format:** Solo\\n**Maximum Time:** 5 Minutes\\nMultiple characters may be portrayed.\\n\\n**Judging — 100 Marks**\\n* Acting — 30\\n* Voice Modulation — 20\\n* Expressions — 20\\n* Creativity — 15\\n* Stage Presence — 15' },
      { title: '5. STAND-UP COMEDY', desc: '**Format:** Solo\\n**Maximum Time:** 5 Minutes\\n\\n**Judging — 100 Marks**\\n* Content & Originality — 25\\n* Comic Timing — 25\\n* Delivery — 20\\n* Audience Engagement — 15\\n* Stage Presence — 15' },
      { title: '6. MIMICRY', desc: '**Format:** Solo\\n**Maximum Time:** 5 Minutes\\n\\n**Judging — 100 Marks**\\n* Voice Accuracy — 30\\n* Expressions — 20\\n* Characterization — 20\\n* Creativity — 15\\n* Stage Presence — 15' },
      { title: '7. INSTRUMENTAL MUSIC', desc: '**Format:** Solo or group\\n**Maximum Time:** 5 Minutes\\n\\n**Judging — 100 Marks**\\n* Technical Skill — 30\\n* Rhythm & Timing — 20\\n* Musicality — 20\\n* Creativity — 15\\n* Overall Performance — 15' },
      { title: '8. MIME', desc: '**Format:** Solo or group\\n**Maximum Time:** 5 Minutes\\n\\n**Judging — 100 Marks**\\n* Expressions — 25\\n* Body Language — 25\\n* Story/Message — 20\\n* Creativity — 15\\n* Overall Impact — 15' },
      { title: '9. LIVE ART', desc: '**Format:** Solo\\n**Maximum Time:** 10 Minutes\\n\\n**Judging — 100 Marks**\\n* Creativity — 25\\n* Technique — 25\\n* Concept — 20\\n* Neatness — 15\\n* Time Management — 15' },
    ],
    iconName: 'Sparkles',
    badge: 'Spotlight',
    isActive: true,
  },
  {
    id: 'switch-a-sketch',
    slug: 'switch-a-sketch',
    title: 'SWITCH-A-SKETCH',
    category: 'non-technical',
    tagline: 'Two participants collaboratively create a single artwork while switching turns every 5 minutes.',
    shortDesc: 'Two participants collaboratively create a single artwork while switching turns every 5 minutes.',
    fullDesc: '**Team Format:** Pair\\n\\n**Team Size:** 2 Participants\\n\\n**Drawing Sheet:** One A5-size drawing sheet per pair\\n\\n**Total Time:** 25 Minutes\\n\\n**Concept:**\\nTwo participants collaboratively create a single artwork while switching turns every 5 minutes.\\n\\n**Objective:**\\nCreate a creative, neat and visually appealing artwork while successfully continuing the drawing created by the previous participant.',
    date: '[SYMPOSIUM DATE]',
    time: '11:00 AM - 12:30 PM',
    venue: 'Design Studio Lab',
    fee: 100,
    teamSize: '2 Members',
    prizes: {
      first: '₹2,000 + Certificate',
      second: '₹1,000 + Certificate',
      third: 'Certificate of Merit',
    },
    coordinators: [],
    rules: [
      'Each team must consist of exactly 2 participants.',
      'Organizers will provide one A5-size drawing sheet per pair.',
      'Participants must bring their own drawing materials.',
      'Only the permitted drawing materials should be used.',
      'Total time allotted is 25 minutes.',
      'Participants must switch turns every 5 minutes when instructed.',
      'The participant taking over must continue the existing drawing.',
      'Switching is compulsory.',
      'Failure to switch at the announced 5-minute interval may result in disqualification.',
      'Participants must stop drawing immediately when the 25-minute time limit ends.',
      'The artwork will be judged based on: Creativity, Neatness, Proper use of the sheet, Overall appearance.',
      'The final artwork should be complete, neat, creative and visually appealing.',
      'Any violation of event rules may lead to disqualification.',
      'The judges\\' decision will be final and binding.',
    ],
    rounds: [
      { title: 'Collaborative Drawing Challenge', desc: '1. Each pair receives one A5-size drawing sheet.\\n2. The pair begins creating one single drawing together.\\n3. Participants draw for 5 minutes.\\n4. At the end of every 5-minute interval, participants must switch turns.\\n5. The participant taking over must continue the existing artwork.\\n6. The drawing continues through each switching interval.\\n7. The total drawing time is 25 minutes.\\n8. Participants must stop immediately when the 25-minute time limit ends.' },
      { title: 'Allowed Materials', desc: 'Participants may use:\\n* Pencil\\n* Black pen\\n* Blue pen\\n* Sketch pens\\n\\nParticipants must bring their own drawing materials.' },
    ],
    iconName: 'Palette',
    badge: 'Creative',
    isActive: true,
  }`
);

fs.writeFileSync('lib/data/events.ts', content, 'utf8');
console.log('Update successful');
